C     -*- fortran -*-
C     This file is autogenerated with f2py (version:1.24.4)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrappythag (pythagf2pywrap, a, b)
      external pythag
      real a
      real b
      real pythagf2pywrap
      real  pythag
      pythagf2pywrap = pythag(a, b)
      end


      subroutine f2pywraprdot3 (rdot3f2pywrap, x, y)
      external rdot3
      real x(3)
      real y(3)
      real rdot3f2pywrap
      real  rdot3
      rdot3f2pywrap = rdot3(x, y)
      end


      subroutine f2pywrapcdot3 (cdot3f2pywrap, x, y)
      external cdot3
      complex x(3)
      complex y(3)
      complex cdot3f2pywrap
      complex  cdot3
      cdot3f2pywrap = cdot3(x, y)
      end


      subroutine f2pywrapgetmisfit (getmisfitf2pywrap, data_tr, sy
     &n_tr, weight, ntr, nsamp, m1, m2, m3, mtype)
      external getmisfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      integer mtype
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real getmisfitf2pywrap
      real  getmisfit
      getmisfitf2pywrap = getmisfit(data_tr, syn_tr, weight, ntr, 
     &nsamp, m1, m2, m3, mtype)
      end


      subroutine f2pywrapl1_misfit (l1_misfitf2pywrap, data_tr, sy
     &n_tr, weight, ntr, nsamp, m1, m2, m3)
      external l1_misfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real l1_misfitf2pywrap
      real  l1_misfit
      l1_misfitf2pywrap = l1_misfit(data_tr, syn_tr, weight, ntr, 
     &nsamp, m1, m2, m3)
      end


      subroutine f2pywrapl1sc_misfit (l1sc_misfitf2pywrap, data_tr
     &, syn_tr, weight, ntr, nsamp, m1, m2, m3)
      external l1sc_misfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real l1sc_misfitf2pywrap
      real  l1sc_misfit
      l1sc_misfitf2pywrap = l1sc_misfit(data_tr, syn_tr, weight, n
     &tr, nsamp, m1, m2, m3)
      end


      subroutine f2pywrapl2_misfit (l2_misfitf2pywrap, data_tr, sy
     &n_tr, weight, ntr, nsamp, m1, m2, m3)
      external l2_misfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real l2_misfitf2pywrap
      real  l2_misfit
      l2_misfitf2pywrap = l2_misfit(data_tr, syn_tr, weight, ntr, 
     &nsamp, m1, m2, m3)
      end


      subroutine f2pywrapl2sc_misfit (l2sc_misfitf2pywrap, data_tr
     &, syn_tr, weight, ntr, nsamp, m1, m2, m3)
      external l2sc_misfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real l2sc_misfitf2pywrap
      real  l2sc_misfit
      l2sc_misfitf2pywrap = l2sc_misfit(data_tr, syn_tr, weight, n
     &tr, nsamp, m1, m2, m3)
      end


      subroutine f2pywrapcorr_misfit (corr_misfitf2pywrap, data_tr
     &, syn_tr, weight, ntr, nsamp, m1, m2, m3)
      external corr_misfit
      integer ntr
      integer nsamp
      real m1
      real m2
      real m3
      real data_tr(3,2000,200)
      real syn_tr(3,2000,200)
      real weight(200)
      real corr_misfitf2pywrap
      real  corr_misfit
      corr_misfitf2pywrap = corr_misfit(data_tr, syn_tr, weight, n
     &tr, nsamp, m1, m2, m3)
      end


      subroutine f2pywrapconv_count (conv_countf2pywrap, phase, ns
     &eg)
      external conv_count
      integer nseg
      integer phase(45,2)
      integer conv_countf2pywrap
      integer  conv_count
      conv_countf2pywrap = conv_count(phase, nseg)
      end


      subroutine f2pywrapfirstnonblank (firstnonblankf2pywrap, buf
     &fer)
      external firstnonblank
      character*120 buffer
      character firstnonblankf2pywrap
      character  firstnonblank
      firstnonblankf2pywrap = firstnonblank(buffer)
      end

